index:
    uri: /
    controller: Controller\HomeController
    httpMethod: [ GET, POST ]


encode:
    uri: /encode                                          #Ceci est la route par défaut
    controller: Controller\EncodeController
    httpMethod: [ GET, POST ]


decode:
    uri: /decode                                          #Ceci est la route par défaut
    controller: Controller\DecodeController
    httpMethod: [ GET, POST ]